### PR TITLE
Refactor benchmarking

### PR DESCRIPTION
**Pull request by divineniiquaye**
- Removed TAMAGUI_TARGET env
- Improved benchmarking UI codes for real world case scenario
- Updated expo to 52
- Updated all libraries to their latest stable version

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
@divineniiquaye let me know if it's good to be merged

**Comment by divineniiquaye** [comment]
> @divineniiquaye let me know if it's good to be merged

Fixed unistyles issue and ready to merge

**Comment by efstathiosntonas** [comment]
amazing, thanks a ton @divineniiquaye, I always promised to update the repo but never had the time to do so. 

Will you update the `COUNT` to 1000 as @jpudysz proposed?

**Comment by divineniiquaye** [comment]
Hopefully, but it means I'll have to run the entire benchmark again and update the scores.

I'll stick to 250 for now, perhaps before the week ends I'll update it to 1000 and add them switch benchmarks

**Comment by AfinaTeam** [comment]
I don't understand. How did third-party libraries become faster than StyleSheet if they internally use it?

**Comment by kotano** [comment]
I don't understand. How did third-party libraries become faster than StyleSheet if they internally use it?

**Comment by Ali-Aref** [comment]
> I don't understand. How did third-party libraries become faster than StyleSheet if they internally use it?

I also have the same question. how this is possible ? can anyone kindly explain ?!

**Comment by jpudysz** [comment]
It's because the number of items is too small. I tested it few times and rendering 1K+ views shows the real performance.

Also it's hard to compare to StyleSheet as it has no features.

**Pull request merged**
