### PR TITLE
feat: add example with react-native-unistyles

### PR DESCRIPTION
**Pull request by jpudysz**
Hello @efstathiosntonas !

I've added the example for `react-native-unistyles` 🦄 !

Can you check it out and meassure performance on your machine?

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
Thanks Jacek! I wish the best for the lib!

**Comment by efstathiosntonas** [comment]
@jpudysz I've added the scores to the tables!

**Comment by jpudysz** [comment]
Wow! Looks awesome 🔥

**Comment by efstathiosntonas** [comment]
great job, on my machine it's 2.5 sec diff from StyleSheet not 4 as you state on docs 🤣

**Comment by jpudysz** [comment]
Thank you @efstathiosntonas , I'm gonna update the docs! 🤣

**Comment by efstathiosntonas** [comment]
@jpudysz I think it would be a good idea to create an example with light/dark theme switcher. This can be tricky for many (new) devs and on the blog article you're not explaining how to inject the proper theme on `UnistylesTheme`  based on `Appearance` or user preference.

**Comment by jpudysz** [comment]
I agree, I will improve the docs in the following days 🙏

**Comment by efstathiosntonas** [comment]
I think the provider should be expanded to support `mode`, `setMode` besides `theme`

**Pull request merged**
